/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows/$id'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated/runs/$runId'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies/$id'
import { Route as AuthenticatedCompaniesIdIndexRouteImport } from './routes/_authenticated/companies/$id.index'
import { Route as AuthenticatedWorkflowsIdEditRouteImport } from './routes/_authenticated/workflows/$id.edit'
import { Route as AuthenticatedCompaniesIdTeamsRouteImport } from './routes/_authenticated/companies/$id.teams'
import { Route as AuthenticatedCompaniesIdTasksRouteImport } from './routes/_authenticated/companies/$id.tasks'
import { Route as AuthenticatedCompaniesIdReportsRouteImport } from './routes/_authenticated/companies/$id.reports'
import { Route as AuthenticatedCompaniesIdIssuesRouteImport } from './routes/_authenticated/companies/$id.issues'
import { Route as AuthenticatedCompaniesIdAgentsRouteImport } from './routes/_authenticated/companies/$id.agents'
import { Route as AuthenticatedCompaniesIdActivityRouteImport } from './routes/_authenticated/companies/$id.activity'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/workflows/$id',
    path: '/workflows/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIdIndexRoute =
  AuthenticatedCompaniesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedWorkflowsIdEditRoute =
  AuthenticatedWorkflowsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedWorkflowsIdRoute,
  } as any)
const AuthenticatedCompaniesIdTeamsRoute =
  AuthenticatedCompaniesIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedCompaniesIdTasksRoute =
  AuthenticatedCompaniesIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedCompaniesIdReportsRoute =
  AuthenticatedCompaniesIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedCompaniesIdIssuesRoute =
  AuthenticatedCompaniesIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedCompaniesIdAgentsRoute =
  AuthenticatedCompaniesIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)
const AuthenticatedCompaniesIdActivityRoute =
  AuthenticatedCompaniesIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedCompaniesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRouteWithChildren
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRouteWithChildren
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/companies/$id/activity': typeof AuthenticatedCompaniesIdActivityRoute
  '/companies/$id/agents': typeof AuthenticatedCompaniesIdAgentsRoute
  '/companies/$id/issues': typeof AuthenticatedCompaniesIdIssuesRoute
  '/companies/$id/reports': typeof AuthenticatedCompaniesIdReportsRoute
  '/companies/$id/tasks': typeof AuthenticatedCompaniesIdTasksRoute
  '/companies/$id/teams': typeof AuthenticatedCompaniesIdTeamsRoute
  '/workflows/$id/edit': typeof AuthenticatedWorkflowsIdEditRoute
  '/companies/$id/': typeof AuthenticatedCompaniesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/companies/$id/activity': typeof AuthenticatedCompaniesIdActivityRoute
  '/companies/$id/agents': typeof AuthenticatedCompaniesIdAgentsRoute
  '/companies/$id/issues': typeof AuthenticatedCompaniesIdIssuesRoute
  '/companies/$id/reports': typeof AuthenticatedCompaniesIdReportsRoute
  '/companies/$id/tasks': typeof AuthenticatedCompaniesIdTasksRoute
  '/companies/$id/teams': typeof AuthenticatedCompaniesIdTeamsRoute
  '/workflows/$id/edit': typeof AuthenticatedWorkflowsIdEditRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRouteWithChildren
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/workflows/$id': typeof AuthenticatedWorkflowsIdRouteWithChildren
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/companies/$id/activity': typeof AuthenticatedCompaniesIdActivityRoute
  '/_authenticated/companies/$id/agents': typeof AuthenticatedCompaniesIdAgentsRoute
  '/_authenticated/companies/$id/issues': typeof AuthenticatedCompaniesIdIssuesRoute
  '/_authenticated/companies/$id/reports': typeof AuthenticatedCompaniesIdReportsRoute
  '/_authenticated/companies/$id/tasks': typeof AuthenticatedCompaniesIdTasksRoute
  '/_authenticated/companies/$id/teams': typeof AuthenticatedCompaniesIdTeamsRoute
  '/_authenticated/workflows/$id/edit': typeof AuthenticatedWorkflowsIdEditRoute
  '/_authenticated/companies/$id/': typeof AuthenticatedCompaniesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enterprise'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/agents'
    | '/approvals'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/workspace'
    | '/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/companies/$id'
    | '/runs/$runId'
    | '/workflows/$id'
    | '/companies/'
    | '/workflows/'
    | '/companies/$id/activity'
    | '/companies/$id/agents'
    | '/companies/$id/issues'
    | '/companies/$id/reports'
    | '/companies/$id/tasks'
    | '/companies/$id/teams'
    | '/workflows/$id/edit'
    | '/companies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enterprise'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/agents'
    | '/approvals'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/workspace'
    | '/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/runs/$runId'
    | '/workflows/$id'
    | '/companies'
    | '/workflows'
    | '/companies/$id/activity'
    | '/companies/$id/agents'
    | '/companies/$id/issues'
    | '/companies/$id/reports'
    | '/companies/$id/tasks'
    | '/companies/$id/teams'
    | '/workflows/$id/edit'
    | '/companies/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/enterprise'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/_authenticated/agents'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/settings'
    | '/_authenticated/workspace'
    | '/_authenticated/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_authenticated/companies/$id'
    | '/_authenticated/runs/$runId'
    | '/_authenticated/workflows/$id'
    | '/_authenticated/companies/'
    | '/_authenticated/workflows/'
    | '/_authenticated/companies/$id/activity'
    | '/_authenticated/companies/$id/agents'
    | '/_authenticated/companies/$id/issues'
    | '/_authenticated/companies/$id/reports'
    | '/_authenticated/companies/$id/tasks'
    | '/_authenticated/companies/$id/teams'
    | '/_authenticated/workflows/$id/edit'
    | '/_authenticated/companies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  SolutionsRoute: typeof SolutionsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/$id': {
      id: '/_authenticated/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$id/': {
      id: '/_authenticated/companies/$id/'
      path: '/'
      fullPath: '/companies/$id/'
      preLoaderRoute: typeof AuthenticatedCompaniesIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/workflows/$id/edit': {
      id: '/_authenticated/workflows/$id/edit'
      path: '/edit'
      fullPath: '/workflows/$id/edit'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdEditRouteImport
      parentRoute: typeof AuthenticatedWorkflowsIdRoute
    }
    '/_authenticated/companies/$id/teams': {
      id: '/_authenticated/companies/$id/teams'
      path: '/teams'
      fullPath: '/companies/$id/teams'
      preLoaderRoute: typeof AuthenticatedCompaniesIdTeamsRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/companies/$id/reports': {
      id: '/_authenticated/companies/$id/reports'
      path: '/reports'
      fullPath: '/companies/$id/reports'
      preLoaderRoute: typeof AuthenticatedCompaniesIdReportsRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/companies/$id/tasks': {
      id: '/_authenticated/companies/$id/tasks'
      path: '/tasks'
      fullPath: '/companies/$id/tasks'
      preLoaderRoute: typeof AuthenticatedCompaniesIdTasksRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/companies/$id/issues': {
      id: '/_authenticated/companies/$id/issues'
      path: '/issues'
      fullPath: '/companies/$id/issues'
      preLoaderRoute: typeof AuthenticatedCompaniesIdIssuesRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/companies/$id/agents': {
      id: '/_authenticated/companies/$id/agents'
      path: '/agents'
      fullPath: '/companies/$id/agents'
      preLoaderRoute: typeof AuthenticatedCompaniesIdAgentsRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
    '/_authenticated/companies/$id/activity': {
      id: '/_authenticated/companies/$id/activity'
      path: '/activity'
      fullPath: '/companies/$id/activity'
      preLoaderRoute: typeof AuthenticatedCompaniesIdActivityRouteImport
      parentRoute: typeof AuthenticatedCompaniesIdRoute
    }
  }
}

interface AuthenticatedCompaniesIdRouteChildren {
  AuthenticatedCompaniesIdActivityRoute: typeof AuthenticatedCompaniesIdActivityRoute
  AuthenticatedCompaniesIdAgentsRoute: typeof AuthenticatedCompaniesIdAgentsRoute
  AuthenticatedCompaniesIdIssuesRoute: typeof AuthenticatedCompaniesIdIssuesRoute
  AuthenticatedCompaniesIdReportsRoute: typeof AuthenticatedCompaniesIdReportsRoute
  AuthenticatedCompaniesIdTasksRoute: typeof AuthenticatedCompaniesIdTasksRoute
  AuthenticatedCompaniesIdTeamsRoute: typeof AuthenticatedCompaniesIdTeamsRoute
  AuthenticatedCompaniesIdIndexRoute: typeof AuthenticatedCompaniesIdIndexRoute
}

const AuthenticatedCompaniesIdRouteChildren: AuthenticatedCompaniesIdRouteChildren =
  {
    AuthenticatedCompaniesIdActivityRoute:
      AuthenticatedCompaniesIdActivityRoute,
    AuthenticatedCompaniesIdAgentsRoute: AuthenticatedCompaniesIdAgentsRoute,
    AuthenticatedCompaniesIdIssuesRoute: AuthenticatedCompaniesIdIssuesRoute,
    AuthenticatedCompaniesIdReportsRoute: AuthenticatedCompaniesIdReportsRoute,
    AuthenticatedCompaniesIdTasksRoute: AuthenticatedCompaniesIdTasksRoute,
    AuthenticatedCompaniesIdTeamsRoute: AuthenticatedCompaniesIdTeamsRoute,
    AuthenticatedCompaniesIdIndexRoute: AuthenticatedCompaniesIdIndexRoute,
  }

const AuthenticatedCompaniesIdRouteWithChildren =
  AuthenticatedCompaniesIdRoute._addFileChildren(
    AuthenticatedCompaniesIdRouteChildren,
  )

interface AuthenticatedWorkflowsIdRouteChildren {
  AuthenticatedWorkflowsIdEditRoute: typeof AuthenticatedWorkflowsIdEditRoute
}

const AuthenticatedWorkflowsIdRouteChildren: AuthenticatedWorkflowsIdRouteChildren =
  {
    AuthenticatedWorkflowsIdEditRoute: AuthenticatedWorkflowsIdEditRoute,
  }

const AuthenticatedWorkflowsIdRouteWithChildren =
  AuthenticatedWorkflowsIdRoute._addFileChildren(
    AuthenticatedWorkflowsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRouteWithChildren
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRouteWithChildren
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRouteWithChildren,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRouteWithChildren,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  SolutionsRoute: SolutionsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
