/**
 * WorkflowExecutionPanel.tsx — Right-side Execution Pipeline
 * 
 * Manages the full workflow execution lifecycle:
 * 1. INPUT phase: User describes task + attaches files
 * 2. RUNNING phase: Sequential agent execution with live status
 * 3. COMPLETE phase: Results displayed in OutputViewer
 * 
 * MOCKED:
 * - Execution is simulated with setTimeout (1.5-3s per agent)
 * - Output is generated by generateMockOutput() based on agent name
 * - File list for code agents is hardcoded
 * 
 * TO INTEGRATE:
 * - Call real LLM APIs sequentially via Edge Functions
 * - Stream each agent's output in real-time
 * - Upload attached files to storage, pass URLs to agents
 * - Store execution history in database
 * 
 * DO NOT CHANGE:
 * - Panel width (380px) and spring animation
 * - Phase state machine (input → running → complete)
 * - The 3-section layout (header | steps | output)
 */

import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { AgentStepTracker, type AgentStep } from "./AgentStepTracker";
import { OutputViewer, type WorkflowOutput } from "./OutputViewer";
import { useWorkflowOutput } from "@/lib/workflow-output-context";
import { useTabContext } from "@/lib/tab-context";
import { Send, Paperclip, X, Sparkles, FileText, ExternalLink, Bot, FileCode } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import type { Node, Edge } from "reactflow";

/**
 * Topological sort — derives execution order from React Flow edges.
 * Agents without incoming edges run first. Unconnected agents run last.
 * This is production-ready logic — no mock here.
 */
function getExecutionOrder(nodes: Node[], edges: Edge[]): Node[] {
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();
  nodes.forEach((n) => { inDegree.set(n.id, 0); adj.set(n.id, []); });
  edges.forEach((e) => {
    adj.get(e.source)?.push(e.target);
    inDegree.set(e.target, (inDegree.get(e.target) || 0) + 1);
  });
  const queue = nodes.filter((n) => (inDegree.get(n.id) || 0) === 0).map((n) => n.id);
  const order: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    order.push(id);
    for (const next of adj.get(id) || []) {
      const deg = (inDegree.get(next) || 1) - 1;
      inDegree.set(next, deg);
      if (deg === 0) queue.push(next);
    }
  }
  nodes.forEach((n) => { if (!order.includes(n.id)) order.push(n.id); });
  return order.map((id) => nodes.find((n) => n.id === id)!).filter(Boolean);
}

/**
 * MOCKED — Generates fake agent output based on agent name keywords.
 * TO INTEGRATE: Replace with actual LLM API call passing task + previous agent's output.
 */
function generateMockOutput(agentName: string, taskInput: string): string {
  const lower = agentName.toLowerCase();
  if (lower.includes("research") || lower.includes("data") || lower.includes("strat")) {
    return `# Research Findings\n\n## Key Insights\n- Analyzed the topic: "${taskInput.slice(0, 50)}..."\n- Found 12 relevant data points\n- Market trend indicates 23% growth\n\n## Recommendations\n1. Focus on emerging patterns\n2. Consider cross-referencing with industry reports\n3. Validate with primary sources`;
  }
  if (lower.includes("write") || lower.includes("copy") || lower.includes("doc") || lower.includes("story")) {
    return `# Generated Content\n\n${taskInput.slice(0, 30)}...\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\n## Section 1\nDetailed analysis and comprehensive coverage of the requested topic with supporting evidence and citations.\n\n## Section 2\nFurther elaboration with practical examples and actionable recommendations.`;
  }
  if (lower.includes("code") || lower.includes("debug") || lower.includes("test") || lower.includes("archi")) {
    return `## Code Review Summary\n\n- Analyzed codebase structure\n- Found 3 potential improvements\n- Suggested 2 optimizations\n\n\`\`\`typescript\n// Optimized implementation\nexport function process(data: Input): Output {\n  return transform(validate(data));\n}\n\`\`\`\n\n### Action Items\n- Refactor data layer\n- Add error boundaries\n- Improve type safety`;
  }
  return `## Agent Output\n\nProcessed task: "${taskInput.slice(0, 60)}"\n\n- Analysis complete\n- Results verified\n- Ready for next stage`;
}

interface WorkflowExecutionPanelProps {
  nodes: Node[];
  edges: Edge[];
  onClose: () => void;
  /** Pre-filled task from AI Workflow Generator — skips redundant input */
  initialTask?: string;
  /** Workflow ID for output storage — used to open output in a separate tab */
  workflowId?: string;
}

export function WorkflowExecutionPanel({ nodes, edges, onClose, initialTask = "", workflowId = "new" }: WorkflowExecutionPanelProps) {
  const [taskInput, setTaskInput] = useState(initialTask);
  const [attachedFiles, setAttachedFiles] = useState<string[]>([]);
  const [steps, setSteps] = useState<AgentStep[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [finalOutput, setFinalOutput] = useState<WorkflowOutput | null>(null);
  /** Phase state machine: input → running → complete */
  const [phase, setPhase] = useState<"input" | "running" | "complete">("input");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const navigate = useNavigate();
  const { setOutput } = useWorkflowOutput();
  const { openApp } = useTabContext();

  /** MOCKED — File attach. Stores filename only, no real upload. */
  const handleAttachFile = () => fileInputRef.current?.click();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    setAttachedFiles((prev) => [...prev, ...files.map((f) => f.name)]);
  };

  /**
   * Main execution handler.
   * 
   * MOCKED — Runs agents sequentially with simulated delays.
   * Each agent gets 1.5-3s of "thinking" time, then receives mock output.
   * 
   * TO INTEGRATE:
   * 1. For each agent in order, call Edge Function with:
   *    - Agent's system prompt (from node.data.prompt)
   *    - Previous agent's output (or user task input for first agent)
   *    - Model preference (from node.data.model)
   *    - Temperature (from node.data.temperature)
   * 2. Stream response tokens into step.output
   * 3. On completion, feed output to next agent
   */
  /**
   * Main execution handler.
   * 
   * PRODUCTION-READY:
   * 1. Transmits the full ReactFlow DAG + Task input to the Ensemble Backend.
   * 2. Sequentially executes agents via the DAGWorkflowEngine.
   * 3. Harvests physical artifacts (Word/Excel/PDF) generated during the run.
   */
  const handleRun = async () => {
    if (!taskInput.trim() || nodes.length === 0) return;

    setIsRunning(true);
    setPhase("running");

    const orderedNodes = getExecutionOrder(nodes, edges);
    const initialSteps: AgentStep[] = orderedNodes.map((n) => ({
      id: n.id,
      agentName: (n.data.label as string)?.replace(/^[^\w]*/, "").trim() || "Agent",
      emoji: (n.data.label as string)?.split(" ")[0] || "🤖",
      status: "pending" as const,
    }));
    setSteps(initialSteps);

    try {
      // 1. Execute the Workflow on the Backend
      const response = await fetch("http://127.0.0.1:8088/api/workflows/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: workflowId,
          nodes,
          edges,
          initialInput: taskInput
        })
      });

      if (!response.ok) throw new Error("Backend execution failed");
      const result = await response.json();

      // 2. Update UI with real results from each step
      setSteps(result.steps.map((s: any) => ({
        id: s.id,
        agentName: s.agent_name,
        emoji: "🤖",
        status: "done" as const,
        output: s.output,
        duration: s.duration || 2
      })));

      // 3. Harvest generated artifacts (Word, Excel, PDF, code files)
      const artifactResp = await fetch(`http://127.0.0.1:8088/api/workflows/${workflowId}/artifacts`);
      const artifacts = artifactResp.ok ? await artifactResp.json() : [];

      // Collect files from all steps (extracted code blocks)
      const stepFiles = result.steps.flatMap((s: any) => s.files || []);

      // 4. Build final results object
      const allMarkdown = result.steps.map((s: any) => `\n\n---\n\n### ${s.agent_name}\n\n${s.output}`).join("");

      const finalResult: WorkflowOutput = {
        markdown: `# Workflow Results\n\n**Task:** ${taskInput}\n\n**Agents:** ${result.steps.length} executed successfully\n${allMarkdown}`,
        files: stepFiles.length > 0 
          ? stepFiles.map((f: any) => ({
              path: f.path,
              content: `[File: ${f.name}]`,
              language: f.language
            }))
          : artifacts.length > 0 
            ? artifacts.map((a: any) => ({
                path: a.name,
                content: `[Binary File: ${a.type}]`,
                language: a.type
              }))
            : undefined,
        workflowId  // Pass the workflow ID for preview fetching
      };

      setFinalOutput(finalResult);
      setPhase("complete");

      // 5. Commit to Global Output Store
      setOutput(workflowId, {
        title: `Workflow Results`,
        task: taskInput,
        agentCount: result.steps.length,
        output: finalResult,
        completedAt: new Date(),
      });

    } catch (err) {
      console.error("❌ Workflow Execution Error:", err);
      // Fallback to error display in tracker
      setSteps(prev => prev.map(s => s.status === "running" ? { ...s, status: "pending" } : s));
      setPhase("input"); // Reset on hard failure
    } finally {
      setIsRunning(false);
    }
  };

  /** Opens workflow output in a dedicated full-width tab */
  const handleOpenInTab = () => {
    openApp({
      id: `workflow-output-${workflowId}`,
      title: "Workflow Output",
      url: `/workflow-output/${workflowId}`,
      icon: FileCode,
      description: "Workflow execution results",
    });
    navigate(`/workflow-output/${workflowId}`);
  };

  return (
    <motion.div
      initial={{ width: 0, opacity: 0 }}
      animate={{ width: 380, opacity: 1 }}
      exit={{ width: 0, opacity: 0 }}
      transition={{ type: "spring", damping: 25, stiffness: 300 }}
      className="h-full border-l border-border/50 bg-card/60 backdrop-blur-2xl flex flex-col shrink-0 overflow-hidden"
    >
      {/* Header — shows current phase label */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border/50">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-sm font-semibold text-foreground">
            {phase === "input" ? "Run Workflow" : phase === "running" ? "Executing..." : "Results"}
          </span>
        </div>
        {/* Close button — closes the entire execution panel */}
        <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={onClose}>
          <X className="h-3.5 w-3.5" />
        </Button>
      </div>

      {/* Phase 1: Task Input */}
      {phase === "input" && (
        <div className="p-4 space-y-3 border-b border-border/30">
          <div className="relative">
            <Textarea
              value={taskInput}
              onChange={(e) => setTaskInput(e.target.value)}
              placeholder="Describe your task... e.g., 'Research AI trends and write a blog post'"
              className="min-h-[100px] bg-secondary/30 border-border/50 text-sm resize-none pr-10"
            />
          </div>

          {/* Attached files list — MOCKED: filename only, no upload */}
          <AnimatePresence>
            {attachedFiles.length > 0 && (
              <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} className="flex flex-wrap gap-1.5 overflow-hidden">
                {attachedFiles.map((f, i) => (
                  <span key={i} className="flex items-center gap-1 text-[10px] bg-secondary/50 rounded px-2 py-1 text-muted-foreground">
                    <FileText className="h-2.5 w-2.5" /> {f}
                    {/* Remove individual file from list */}
                    <button onClick={() => setAttachedFiles((prev) => prev.filter((_, idx) => idx !== i))} className="hover:text-foreground">
                      <X className="h-2.5 w-2.5" />
                    </button>
                  </span>
                ))}
              </motion.div>
            )}
          </AnimatePresence>

          <div className="flex items-center gap-2">
            <input type="file" ref={fileInputRef} className="hidden" multiple onChange={handleFileChange} />
            {/* Attach button — opens native file picker (MOCKED: no upload) */}
            <Button variant="outline" size="sm" className="h-8 text-xs gap-1.5" onClick={handleAttachFile}>
              <Paperclip className="h-3 w-3" /> Attach
            </Button>
            {/* Run button — starts execution pipeline */}
            <Button
              size="sm"
              className="h-8 text-xs gap-1.5 flex-1"
              onClick={handleRun}
              disabled={!taskInput.trim() || nodes.length === 0}
            >
              <Send className="h-3 w-3" /> Run Workflow
            </Button>
          </div>

          {/* Warning when canvas is empty */}
          {nodes.length === 0 && (
            <p className="text-[11px] text-muted-foreground text-center">Add agents to the canvas first</p>
          )}
        </div>
      )}

      {/* Phase 2 & 3: Agent execution steps (timeline) */}
      {(phase === "running" || phase === "complete") && (
        <div className={`${phase === "complete" ? "max-h-[40%]" : "flex-1"} border-b border-border/30`}>
          <AgentStepTracker steps={steps} />
        </div>
      )}

      {/* Phase 3: Compact results summary + "Open in Tab" button */}
      {phase === "complete" && finalOutput && (
        <div className="flex-1 min-h-0 flex flex-col">
          {/* Compact summary */}
          <div className="p-4 space-y-3">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium text-foreground">Results Ready</span>
            </div>
            
            {/* Summary badges */}
            <div className="flex flex-wrap gap-1.5">
              {finalOutput.markdown && (
                <Badge variant="secondary" className="text-[10px] gap-1">
                  <FileText className="h-2.5 w-2.5" />
                  {finalOutput.markdown.split(/\s+/).length} words
                </Badge>
              )}
              {finalOutput.files && (
                <Badge variant="secondary" className="text-[10px] gap-1">
                  <FileCode className="h-2.5 w-2.5" />
                  {finalOutput.files.length} files
                </Badge>
              )}
              <Badge variant="secondary" className="text-[10px] gap-1">
                <Bot className="h-2.5 w-2.5" />
                {steps.length} agents
              </Badge>
            </div>

            {/* Markdown preview — first ~8 lines */}
            {finalOutput.markdown && (
              <div className="bg-secondary/30 rounded-lg p-3 border border-border/30">
                <p className="text-[11px] text-muted-foreground line-clamp-4 leading-relaxed">
                  {finalOutput.markdown.split("\n").filter(l => l.trim() && !l.startsWith("#") && !l.startsWith("---")).slice(0, 3).join(" ")}
                </p>
              </div>
            )}

            {/* Open in Tab — primary action */}
            <Button
              size="sm"
              className="w-full h-9 text-xs gap-2 font-semibold"
              onClick={handleOpenInTab}
            >
              <ExternalLink className="h-3.5 w-3.5" /> Open in Tab
            </Button>
          </div>
        </div>
      )}

      {/* Re-run button — resets to input phase */}
      {phase === "complete" && (
        <div className="p-3 border-t border-border/30">
          <Button
            variant="outline"
            size="sm"
            className="w-full h-8 text-xs gap-1.5"
            onClick={() => { setPhase("input"); setSteps([]); setFinalOutput(null); }}
          >
            Run Again
          </Button>
        </div>
      )}
    </motion.div>
  );
}
