import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { Network, Bot, Braces, Terminal, ArrowRight, Layers, Workflow, CheckCircle2 } from "lucide-react";

const Platform = () => {
  const navigate = useNavigate();

  const fadeIn = {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.6 }
  };

  return (
    <div className="w-full min-h-screen bg-[linear-gradient(180deg,#e8edf3_0%,#eef2f7_100%)] font-sans pt-24 pb-20 text-foreground">
      {/* Header */}
      <section className="px-6 py-20 text-center max-w-4xl mx-auto relative z-10">
        <motion.div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary mb-6 text-sm font-bold" {...fadeIn}>
          <Layers className="w-4 h-4" /> The Esemble Engine
        </motion.div>
        <motion.h1 className="text-5xl md:text-7xl font-black tracking-tighter mb-6" {...fadeIn}>
          Built for <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-blue-400">Scale</span>. Engineered for <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-accent">Impact</span>.
        </motion.h1>
        <motion.p className="text-xl text-muted-foreground leading-relaxed" {...fadeIn}>
          Dive into the architecture that powers the next generation of AI workforces. A proprietary Directed Acyclic Graph (DAG) execution engine meets an enterprise-grade agent registry.
        </motion.p>
      </section>

      {/* Core Components Grid */}
      <section className="px-6 py-16 max-w-7xl mx-auto relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <FeatureBlock 
            icon={Workflow}
            title="DAG Workflow Engine"
            description="Our custom execution engine parses visual pipelines into highly optimized Directed Acyclic Graphs. It automatically detects parallel execution paths, prevents infinite loops, and manages complex state handoffs between agents with zero data loss."
            points={["Auto-parallelization", "State hydration & recovery", "Cycle detection"]}
          />
          <FeatureBlock 
            icon={Bot}
            title="Dynamic Agent Registry"
            description="A centralized hub managing over 180 specialized AI profiles. Each agent comes pre-configured with strict behavioral bounds, context windows, and specific tool access limits to ensure predictable, deterministic outputs."
            points={["180+ Native Specialists", "Version controlled prompts", "Hot-swappable models (GPT-4o, Claude 3.5, Gemini)"]}
          />
          <FeatureBlock 
            icon={Terminal}
            title="Secure Code Sandboxing"
            description="When agents write code, Esemble executes it securely. Our isolated Docker-based execution environments ensure that Python, Node.js, and Bash scripts generated by AI run safely without exposing your core infrastructure."
            points={["Ephemeral containers", "Network egress control", "Resource limits (CPU/RAM)"]}
          />
          <FeatureBlock 
            icon={Braces}
            title="Universal API Connectors"
            description="Agents aren't trapped in a vacuum. Connect your workflows to Slack, Jira, Feishu, and your internal REST/GraphQL APIs. Data flows seamlessly in and out of the Esemble ecosystem."
            points={["OAuth2 management", "Webhook triggers", "Custom HTTP headers"]}
          />
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-24 text-center">
        <motion.div className="max-w-3xl mx-auto p-12 rounded-[2rem] border border-slate-200/80 bg-white/75 backdrop-blur-xl shadow-[0_18px_60px_rgba(15,23,42,0.08)]" {...fadeIn}>
          <h2 className="text-3xl font-black mb-4">Experience the Platform</h2>
          <p className="text-muted-foreground mb-8">See how our engine parses, parallelizes, and executes complex tasks in real-time.</p>
          <Button size="lg" className="rounded-full px-8 font-bold" onClick={() => navigate('/auth')}>
            Start Building <ArrowRight className="w-4 h-4 ml-2" />
          </Button>
        </motion.div>
      </section>
    </div>
  );
};

const FeatureBlock = ({ icon: Icon, title, description, points }: any) => (
  <motion.div 
    initial={{ opacity: 0, y: 20 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    className="p-8 md:p-10 rounded-3xl border border-slate-200/80 bg-white/75 hover:bg-white transition-colors shadow-[0_12px_40px_rgba(15,23,42,0.06)]"
  >
    <div className="w-14 h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-6">
      <Icon className="w-7 h-7 text-primary" />
    </div>
    <h3 className="text-2xl font-bold mb-4">{title}</h3>
    <p className="text-muted-foreground mb-6 leading-relaxed">{description}</p>
    <ul className="space-y-3">
      {points.map((p: string, i: number) => (
        <li key={i} className="flex items-center gap-3 text-sm font-medium text-foreground/80">
          <CheckCircle2 className="w-4 h-4 text-emerald-500" /> {p}
        </li>
      ))}
    </ul>
  </motion.div>
);

export default Platform;
